name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftpupload.net }}
          username: ${{ secrets.if0_41767982 }}
          password: ${{ secrets.FTP_ou2AsaiKfnGT }}
          local-dir: ./
          server-dir: /htdocs/
          # Mengabaikan folder .git dan .github agar tidak ikut terupload ke hosting
          exclude: |
            **/.git*
            **/.git*/**
            **/.github*/**
